# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\application.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(843, 871)
        self.centralwidget = QtWidgets.QWidget(Application)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.menu_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.menu_tab.setEnabled(True)
        self.menu_tab.setAutoFillBackground(False)
        self.menu_tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.menu_tab.setObjectName("menu_tab")
        self.logging_tab = QtWidgets.QWidget()
        self.logging_tab.setObjectName("logging_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.logging_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dist_label = QtWidgets.QLabel(self.logging_tab)
        self.dist_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dist_label.setObjectName("dist_label")
        self.gridLayout_3.addWidget(self.dist_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.start_button = QtWidgets.QPushButton(self.logging_tab)
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setObjectName("start_button")
        self.button_layout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.logging_tab)
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setObjectName("stop_button")
        self.button_layout.addWidget(self.stop_button)
        self.reset_button = QtWidgets.QPushButton(self.logging_tab)
        self.reset_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_button.setObjectName("reset_button")
        self.button_layout.addWidget(self.reset_button)
        self.main_layout.addLayout(self.button_layout)
        self.option_layout = QtWidgets.QHBoxLayout()
        self.option_layout.setObjectName("option_layout")
        self.check_box_show_graph = QtWidgets.QCheckBox(self.logging_tab)
        self.check_box_show_graph.setObjectName("check_box_show_graph")
        self.option_layout.addWidget(self.check_box_show_graph)
        self.status_label = QtWidgets.QLabel(self.logging_tab)
        self.status_label.setObjectName("status_label")
        self.option_layout.addWidget(self.status_label)
        self.main_layout.addLayout(self.option_layout)
        self.raw_data_graph_layout = QtWidgets.QGridLayout()
        self.raw_data_graph_layout.setSpacing(20)
        self.raw_data_graph_layout.setObjectName("raw_data_graph_layout")
        self.graph_gx = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_gx.setObjectName("graph_gx")
        self.raw_data_graph_layout.addWidget(self.graph_gx, 3, 3, 1, 1)
        self.label_ax = QtWidgets.QLabel(self.logging_tab)
        self.label_ax.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ax.setObjectName("label_ax")
        self.raw_data_graph_layout.addWidget(self.label_ax, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_gz = QtWidgets.QLabel(self.logging_tab)
        self.label_gz.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_gz.setObjectName("label_gz")
        self.raw_data_graph_layout.addWidget(self.label_gz, 4, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_ay = QtWidgets.QLabel(self.logging_tab)
        self.label_ay.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_ay.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_ay.setObjectName("label_ay")
        self.raw_data_graph_layout.addWidget(self.label_ay, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_az = QtWidgets.QLabel(self.logging_tab)
        self.label_az.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_az.setObjectName("label_az")
        self.raw_data_graph_layout.addWidget(self.label_az, 2, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graph_gz = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_gz.setObjectName("graph_gz")
        self.raw_data_graph_layout.addWidget(self.graph_gz, 3, 6, 1, 1)
        self.graph_ax = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_ax.setObjectName("graph_ax")
        self.raw_data_graph_layout.addWidget(self.graph_ax, 1, 3, 1, 1)
        self.graph_az = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_az.setObjectName("graph_az")
        self.raw_data_graph_layout.addWidget(self.graph_az, 1, 6, 1, 1)
        self.graph_gy = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_gy.setObjectName("graph_gy")
        self.raw_data_graph_layout.addWidget(self.graph_gy, 3, 4, 1, 1)
        self.label_gy = QtWidgets.QLabel(self.logging_tab)
        self.label_gy.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_gy.setObjectName("label_gy")
        self.raw_data_graph_layout.addWidget(self.label_gy, 4, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graph_ay = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_ay.setObjectName("graph_ay")
        self.raw_data_graph_layout.addWidget(self.graph_ay, 1, 4, 1, 1)
        self.label_gx = QtWidgets.QLabel(self.logging_tab)
        self.label_gx.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_gx.setObjectName("label_gx")
        self.raw_data_graph_layout.addWidget(self.label_gx, 4, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.main_layout.addLayout(self.raw_data_graph_layout)
        self.gridLayout_3.addLayout(self.main_layout, 0, 0, 1, 1)
        self.vel_label = QtWidgets.QLabel(self.logging_tab)
        self.vel_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vel_label.setObjectName("vel_label")
        self.gridLayout_3.addWidget(self.vel_label, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graph_dist = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_dist.setObjectName("graph_dist")
        self.gridLayout_3.addWidget(self.graph_dist, 1, 0, 1, 1)
        self.graph_vel = QtWidgets.QGraphicsView(self.logging_tab)
        self.graph_vel.setObjectName("graph_vel")
        self.gridLayout_3.addWidget(self.graph_vel, 3, 0, 1, 1)
        self.total_dist_label = QtWidgets.QLabel(self.logging_tab)
        self.total_dist_label.setObjectName("total_dist_label")
        self.gridLayout_3.addWidget(self.total_dist_label, 6, 0, 1, 1)
        self.average_vel_label = QtWidgets.QLabel(self.logging_tab)
        self.average_vel_label.setObjectName("average_vel_label")
        self.gridLayout_3.addWidget(self.average_vel_label, 7, 0, 1, 1)
        self.menu_tab.addTab(self.logging_tab, "")
        self.load_data_tab = QtWidgets.QWidget()
        self.load_data_tab.setObjectName("load_data_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.load_data_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.raw_data_graph_layout_2 = QtWidgets.QGridLayout()
        self.raw_data_graph_layout_2.setSpacing(20)
        self.raw_data_graph_layout_2.setObjectName("raw_data_graph_layout_2")
        self.label_loaded_accel_x = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_accel_x.setObjectName("label_loaded_accel_x")
        self.raw_data_graph_layout_2.addWidget(self.label_loaded_accel_x, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graph_gx_2 = QtWidgets.QGraphicsView(self.load_data_tab)
        self.graph_gx_2.setObjectName("graph_gx_2")
        self.raw_data_graph_layout_2.addWidget(self.graph_gx_2, 3, 3, 1, 1)
        self.graph_ax_2 = QtWidgets.QGraphicsView(self.load_data_tab)
        self.graph_ax_2.setObjectName("graph_ax_2")
        self.raw_data_graph_layout_2.addWidget(self.graph_ax_2, 1, 3, 1, 1)
        self.graph_gz_2 = QtWidgets.QGraphicsView(self.load_data_tab)
        self.graph_gz_2.setObjectName("graph_gz_2")
        self.raw_data_graph_layout_2.addWidget(self.graph_gz_2, 3, 6, 1, 1)
        self.label_loaded_accel_y = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_accel_y.setObjectName("label_loaded_accel_y")
        self.raw_data_graph_layout_2.addWidget(self.label_loaded_accel_y, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graph_ay_2 = QtWidgets.QGraphicsView(self.load_data_tab)
        self.graph_ay_2.setObjectName("graph_ay_2")
        self.raw_data_graph_layout_2.addWidget(self.graph_ay_2, 1, 4, 1, 1)
        self.graph_gy_2 = QtWidgets.QGraphicsView(self.load_data_tab)
        self.graph_gy_2.setObjectName("graph_gy_2")
        self.raw_data_graph_layout_2.addWidget(self.graph_gy_2, 3, 4, 1, 1)
        self.label_loaded_accel_z = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_accel_z.setObjectName("label_loaded_accel_z")
        self.raw_data_graph_layout_2.addWidget(self.label_loaded_accel_z, 2, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graph_az_2 = QtWidgets.QGraphicsView(self.load_data_tab)
        self.graph_az_2.setObjectName("graph_az_2")
        self.raw_data_graph_layout_2.addWidget(self.graph_az_2, 1, 6, 1, 1)
        self.label_loaded_gyro_x = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_gyro_x.setObjectName("label_loaded_gyro_x")
        self.raw_data_graph_layout_2.addWidget(self.label_loaded_gyro_x, 4, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_loaded_gyro_y = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_gyro_y.setObjectName("label_loaded_gyro_y")
        self.raw_data_graph_layout_2.addWidget(self.label_loaded_gyro_y, 4, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_loaded_gyro_z = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_gyro_z.setObjectName("label_loaded_gyro_z")
        self.raw_data_graph_layout_2.addWidget(self.label_loaded_gyro_z, 4, 6, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout_4.addLayout(self.raw_data_graph_layout_2, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.load_button = QtWidgets.QPushButton(self.load_data_tab)
        self.load_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_button.setObjectName("load_button")
        self.gridLayout_2.addWidget(self.load_button, 0, 1, 1, 1)
        self.send_to_line_button = QtWidgets.QPushButton(self.load_data_tab)
        self.send_to_line_button.setObjectName("send_to_line_button")
        self.gridLayout_2.addWidget(self.send_to_line_button, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.option_layout_2 = QtWidgets.QHBoxLayout()
        self.option_layout_2.setObjectName("option_layout_2")
        self.raw_data_option = QtWidgets.QCheckBox(self.load_data_tab)
        self.raw_data_option.setObjectName("raw_data_option")
        self.option_layout_2.addWidget(self.raw_data_option)
        self.processed_data_option = QtWidgets.QCheckBox(self.load_data_tab)
        self.processed_data_option.setObjectName("processed_data_option")
        self.option_layout_2.addWidget(self.processed_data_option)
        self.show_result_option = QtWidgets.QCheckBox(self.load_data_tab)
        self.show_result_option.setObjectName("show_result_option")
        self.option_layout_2.addWidget(self.show_result_option)
        self.gridLayout_4.addLayout(self.option_layout_2, 1, 0, 1, 1)
        self.processed_graph_layout = QtWidgets.QVBoxLayout()
        self.processed_graph_layout.setSpacing(20)
        self.processed_graph_layout.setObjectName("processed_graph_layout")
        self.distance_graph = QtWidgets.QGraphicsView(self.load_data_tab)
        self.distance_graph.setObjectName("distance_graph")
        self.processed_graph_layout.addWidget(self.distance_graph)
        self.label_loaded_distance = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_distance.setObjectName("label_loaded_distance")
        self.processed_graph_layout.addWidget(self.label_loaded_distance, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.velocity_graph = QtWidgets.QGraphicsView(self.load_data_tab)
        self.velocity_graph.setObjectName("velocity_graph")
        self.processed_graph_layout.addWidget(self.velocity_graph)
        self.label_loaded_velocity = QtWidgets.QLabel(self.load_data_tab)
        self.label_loaded_velocity.setObjectName("label_loaded_velocity")
        self.processed_graph_layout.addWidget(self.label_loaded_velocity, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout_4.addLayout(self.processed_graph_layout, 3, 0, 1, 1)
        self.result_layout = QtWidgets.QHBoxLayout()
        self.result_layout.setObjectName("result_layout")
        self.distance_label = QtWidgets.QLabel(self.load_data_tab)
        self.distance_label.setObjectName("distance_label")
        self.result_layout.addWidget(self.distance_label)
        self.average_velocity_label = QtWidgets.QLabel(self.load_data_tab)
        self.average_velocity_label.setEnabled(True)
        self.average_velocity_label.setObjectName("average_velocity_label")
        self.result_layout.addWidget(self.average_velocity_label)
        self.gridLayout_4.addLayout(self.result_layout, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.menu_tab.addTab(self.load_data_tab, "")
        self.gridLayout.addWidget(self.menu_tab, 0, 0, 1, 1)
        Application.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Application)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 26))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        Application.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Application)
        self.statusbar.setObjectName("statusbar")
        Application.setStatusBar(self.statusbar)

        self.retranslateUi(Application)
        self.menu_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "Application"))
        self.dist_label.setText(_translate("Application", "Distance (m)"))
        self.start_button.setText(_translate("Application", "Start"))
        self.stop_button.setText(_translate("Application", "Stop"))
        self.reset_button.setText(_translate("Application", "Reset"))
        self.check_box_show_graph.setText(_translate("Application", "Show raw data graph"))
        self.status_label.setText(_translate("Application", "Status: Off"))
        self.label_ax.setText(_translate("Application", "Accelerometer X"))
        self.label_gz.setText(_translate("Application", "Gyroscope Z"))
        self.label_ay.setText(_translate("Application", "Accelerometer Y"))
        self.label_az.setText(_translate("Application", "Accelerometer Z"))
        self.label_gy.setText(_translate("Application", "Gyroscope Y"))
        self.label_gx.setText(_translate("Application", "Gyroscope X"))
        self.vel_label.setText(_translate("Application", "Velocity (m/s)"))
        self.total_dist_label.setText(_translate("Application", "Total Distance (m) ="))
        self.average_vel_label.setText(_translate("Application", "Average Velocity = "))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.logging_tab), _translate("Application", "Log"))
        self.label_loaded_accel_x.setText(_translate("Application", "Accel X"))
        self.label_loaded_accel_y.setText(_translate("Application", "Accel Y"))
        self.label_loaded_accel_z.setText(_translate("Application", "Accel Z"))
        self.label_loaded_gyro_x.setText(_translate("Application", "Gyro X"))
        self.label_loaded_gyro_y.setText(_translate("Application", "Gyro Y"))
        self.label_loaded_gyro_z.setText(_translate("Application", "Gyro Z"))
        self.load_button.setText(_translate("Application", "Load data"))
        self.send_to_line_button.setText(_translate("Application", "Send to Line"))
        self.raw_data_option.setText(_translate("Application", "Show raw data"))
        self.processed_data_option.setText(_translate("Application", "Show processed data"))
        self.show_result_option.setText(_translate("Application", "Show result"))
        self.label_loaded_distance.setText(_translate("Application", "Distance"))
        self.label_loaded_velocity.setText(_translate("Application", "Veolocity"))
        self.distance_label.setText(_translate("Application", "Distance = "))
        self.average_velocity_label.setText(_translate("Application", "Average Velocity = "))
        self.menu_tab.setTabText(self.menu_tab.indexOf(self.load_data_tab), _translate("Application", "Load"))


